### PR TITLE
fix(respec2html): update Renderer for marked v16 token-based API

### PR DESCRIPTION
**Pull request by marcoscaceres**
## Summary

- marked v16 changed the `Renderer` API: methods now receive **token objects** instead of pre-rendered strings, but `respec2html.js` was still using the v12 API
- This caused a crash (`str.replace is not a function`) any time ReSpec reported an error or warning during `respec2html` runs
- The bug was introduced by #5129 (marked 12 → 16 upgrade) but not caught at the time because the `respec2html` error-rendering path only triggers on actual document errors

## Changes

- All renderer methods updated to accept token objects and use `this.parser.parseInline(token.tokens)` for child content rendering
- `link()` updated to use `token.href` and `token.tokens` instead of positional arguments (v16 changed the signature)
- `list()` updated to iterate `token.items` instead of receiving a pre-rendered body string
- Removed `smartypants` option (removed from marked in v13+, silently ignored since then)

## How to reproduce the bug

Any spec that produces a ReSpec error or warning will crash `respec2html` with:
```
TypeError: str.replace is not a function
  at unescape (respec2html.js:334)
  at Renderer.paragraph (respec2html.js:25)
  at Logger._formatMarkdown (respec2html.js:87)
```

The crash happens because `Logger._formatMarkdown` formats error messages using `marked`, which now passes token objects to `Renderer.paragraph()` instead of strings.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: tools/respec2html.js [hunk 1]
```diff
@@ -1,7 +1,6 @@
 #!/usr/bin/env node
 import { readFile, writeFile } from "fs/promises";
 import colors from "colors";
-import { fileURLToPath } from "url";
 import finalhandler from "finalhandler";
 import http from "http";
```
[the remark this answers is not in the document]
Comment (marcoscaceres) [reply tools/respec2html.js]: These changes are intentionally grouped — they all landed together and share the same Node 24 / marked v16 upgrade context. Splitting them into separate PRs would make the history harder to follow. The PR description has been updated to reflect the full scope.

File: docs/superpowers/specs/2026-03-28-respec-docs-live-audit-prompt.md [hunk 2]
```diff
@@ -0,0 +1,182 @@
...
+## Setup
+
+The ReSpec tools are already installed:
+- `respec2html` is available as a CLI command (via the respec repo)
+- Or run: `node /Users/marcoscaceres/dev/w3c/respec/tools/respec2html.js`
+
+Wiki docs are at: `https://github.com/speced/respec/wiki`
+Or locally: `/Users/marcoscaceres/dev/w3c/respec-wiki/`
+
+Create the spec in: `/tmp/dahut-api/`
```
[the remark this answers is not in the document]
Comment (marcoscaceres) [reply docs/superpowers/specs/2026-03-28-respec-docs-live-audit-prompt.md]: These files have been removed from the branch — they were accidentally committed and have since been cleaned up.

File: docs/superpowers/specs/2026-03-28-session-continuation.md [hunk 3]
```diff
@@ -0,0 +1,73 @@
...
+- #5097 — `actions/download-artifact` v7 (triggered Dependabot rebase, check if ready)
+- #5130 type check if ESLint errors on new files we wrote
+
+### Don't forget
+- The `feat/validate-header-links` branch still has the original header validation feature that needs a PR
+- The error message improvements to `link-to-dfn.js` (scoping hint) and `xref.js` (invalid config hint) are committed to main but not in separate PRs — they were part of the `chore(node24)` commit
+
+## Environment notes
+- npm registry: `https://npm.apple.com`
+- Git: no GPG signing, commits as Marcos Cáceres `<marcosc@apple.com>`
```
[the remark this answers is not in the document]
Comment (marcoscaceres) [reply docs/superpowers/specs/2026-03-28-session-continuation.md]: These files have been removed from the branch — they were accidentally committed and have since been cleaned up.
